name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: tomef96/cancel-workflow-action@073140824b39bf1645b8cd086a422a268f08c206
        with:
          access_token: ${{ github.token }}
      - run: sleep 60
